measurement:
  type: center_mask
  T: 0.992
  terminal_time: 1e-5
  noise_std: 0.1
  hole_ratio: 0.5 # center_mask specific parameter 
  same_normalization: true # true
  normalization_form: "affine"   # "fixed" | "adaptive" | "edm" | "moving"
  stats_mode: "standard"     # "standard" | "robust"
  stats_update_mode: "fixed"
  